version: "3.8"

services:
  speech_recognition:
    container_name: speech_recognition
    build:
      context: ./apis/speech_recognition
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # networks:
    #   - deploy_network